Modal nav hyd 63
ramirofazio/Hydrotek-Web pull request #11
Opened 2023-08-19 00:43 UTC by TomasPerez1

Modal terminado y agregue el componente Categories

2023-08-19 16:17 UTC, ramirofazio commented
Hay que hacer un merge con la rama ResponsiveLanding para terminar de estandarizar el responsive de la nav y unir el drawer con la logica hecha aca 👀

2023-08-21 13:49 UTC, ramirofazio requested changes
Nice job 💯

2023-08-21 13:49 UTC, ramirofazio commented on package-lock.json
Esto no deberia estar en git. agregalo al .gitIgnore (Ya esta agregado en mi rama y en develop creo)

2023-08-21 13:49 UTC, ramirofazio commented on src/components/Categories.jsx
> +                <Listbox.Option value={c.value} className="hover:text-white">
```suggestion
                <Listbox.Option value={c.value} className="hover:text-white p-2 px-3">
```

### Mejor UI

2023-08-21 13:49 UTC, ramirofazio commented on src/components/Categories.jsx
Encontre un Bug al querer hacerle hover sobre "SAFE ROOTS" y "CANASTAS". Chequear eso 👀

2023-08-21 13:49 UTC, ramirofazio commented on src/components/Navbar.jsx
### En este componente deberiamos integrar el ModalNav cuando esta en mobil o Tablet. Hacer merge de la rama "ResponsiveLanding-HYD-65" y unificar 😎 !!

2023-08-21 20:36 UTC, josesantangelo commented on package-lock.json
Esto si deberia estar en git. Si en algun momento rompe una dependencia, o peor: una dependencia de una dependencia, la unica forma de trackearlo es a traves del lock

2023-08-22 03:31 UTC, ramirofazio approved these changes

2023-08-22 13:23 UTC, merged