HYD-107: Re-estructurando router con JWT y flujo de usuarios. [RTM]
ramirofazio/Hydrotek-Web pull request #32
Opened 2023-09-15 04:42 UTC by ramirofazio

>[!NOTE]
> Al momento de entrar en la tarea de user profile me encontré con todo este temita
---
- Solucione el flujo del usuario una vez loggeado, ahora el flujo esta completo y el usuario tiene permisos por así decirlo. Se manejo un estado global de Auth con el `Token` y se actualizo el index.js de las rutas.
- Se agrego `authProvider.js`: Es un componente que esta siempre montado y buscando el JWT activo. una vez que existe se ocupa de declararlo globalmente y dispara la lógica de autorización para cada sección de la pagina. 
---
>[!WARNING]
> Faltaría terminar de sincronizar los cambios con index.js de la API que declara el token y configura el Header. Ya que `authProvider` busca hacer lo mismo de una manera mas **escalable**. Ademas esta la opcion de usar el `token` como una Cookie que es mas seguro! Todo en esta [DOCU](https://dev.to/sanjayttg/jwt-authentication-in-react-with-react-router-1d03), recomiendo leerla.

2023-09-15 16:19 UTC, TomasPerez1 requested changes

2023-09-15 16:19 UTC, TomasPerez1 commented on src/provider/authProvider.jsx
Pasar a un estado de redux con su propio reducer y logica
En vez de  modificar el axios.default agregarel bearer a la instancia de axios Api hydro, en la carpeta api

2023-09-15 18:26 UTC, ramirofazio commented on src/provider/authProvider.jsx
Hablame bien que soy sensible 😢

2023-09-15 19:36 UTC, ramirofazio commented
@TomasPerez1 Ready!

2023-09-19 16:45 UTC, TomasPerez1 approved these changes
nice

2023-09-19 16:45 UTC, merged