Swiper/Carousel Reutilizable [WIP]
ramirofazio/Hydrotek-Web pull request #9
Opened 2023-08-17 23:37 UTC by ramirofazio

- [ ] testing swiper.js
- [ ] adding styles

2023-08-19 01:10 UTC, TomasPerez1 requested changes

2023-08-19 01:10 UTC, TomasPerez1 commented on tailwind.config.js
No me parece adecuado el cambio de los breakpoints ya que no hay dispositivos (o por lo menos no nos vamos a enfocar) tan pequeños como 200px,  y al estar acostumbrado a los  brackpoints default de tailwind [https://tailwindcss.com/docs/container](url) usar las mismas propiedades pero tamaños distintos me parece confuso.
**Propongo:**
. Añadir el breakpoint xs con  un max-width (400px/500px) aprox 

Info para entender en detalle los breakpoints [https://www.freecodecamp.org/news/the-100-correct-way-to-do-css-breakpoints-88d6a5ba1862/](url)

2023-08-21 13:54 UTC, ramirofazio commented on tailwind.config.js
Me parece bien. Habria que borrar los valores y se aplicar por default? O hay que poner los que estan en la docu?

2023-08-21 15:47 UTC, ramirofazio commented
Agregue el Carrousel responsive y lo hice reciclable para utilizar con la prop content. Ejemplo en Carrousel.jsx.

A definir tema de breackpoints, lo solucionaremos en otra rama

2023-08-21 16:36 UTC, TomasPerez1 commented on tailwind.config.js
![image](https://github.com/ramirofazio/Hydrotek-Frontend/assets/101677692/58b7a41e-f077-4f15-bd70-31d82699104a)

2023-08-22 15:57 UTC, ramirofazio commented
Si esta lista para mergear mergeen y sigan con otras tareas! @TomasPerez1 @josesantangelo

2023-08-22 21:53 UTC, merged